### ISSUE TITLE
Create widgets to specific post?

### ISSUE THREAD

**Issue by Crysikrend** [mktcode/steemit-widgets#2]
Hey there, great job on this.

I'm trying to work with the plugin and trying to integrate it with my git pages blog, but I'm struggling a bit on a use case, so I just wanted to formally inquire about it so that if there is a way to do this other people will know.

Is there an easy way to simply 'get a post' from Steemit? It would be nice to have a blog post that I write for my website, but show info from a Steemit post such as upvotes etc. This way I can still style the blog and write it in the way I like to, but I can bounce people between Steemit and my site. I can show the number of resteems etc, and forward people to Steemit if they enjoyed the article. I would simply paste the URL to the Steemit post in my metadata in markdown and my static site generator would then insert it into a html template with your widget code inside it. This would also be good for getting the tags of a post?

I don't know how to change the code in this way but I'm also struggling to see if it's actually possible. Thanks for reading!

**Comment by mktcode** [comment]
Hi! Yes, you can display a single full steem post on your website.
Here's the related section in the docs: https://mktcode.github.io/steemit-widgets/#options-full-post
Hope this already helps you. If you need more help, ask here. :)

**Comment by Crysikrend** [comment]
Hey again!

I believe your readme file on the repo is mismatched as that's where I was looking! It is obvious to me now that I simply have to set the permlink value to the latter of the URL, but your GitHub readme says that permlink is actually an integer value 😊

Thanks for pointing me in the right direction!

**Comment by mktcode** [comment]
Oh ok.... yes, this whole repo hasn't been touched for a while. Feel free to submit PRs... :P
